# Generated by Django 4.1.7 on 2023-05-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_name'),
        ('user', '0003_user_one_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='one_department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='department.department', verbose_name='部门'),
        ),
    ]
