# Generated by Django 4.1.7 on 2023-05-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_one_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='出生日期'),
        ),
    ]
