# Generated by Django 4.1.7 on 2023-06-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_superior_alter_department_name'),
        ('user', '0007_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(help_text='出生日期', null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(help_text='入职日期', null=True, verbose_name='入职日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, help_text='性别', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='头像', null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(help_text='手机号', max_length=11, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='one_department',
            field=models.ForeignKey(default='', help_text='部门', null=True, on_delete=django.db.models.deletion.PROTECT, to='department.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(help_text='职位', max_length=10, verbose_name='职位'),
        ),
    ]
