# Generated by Django 4.1.7 on 2023-06-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Superior',
            field=models.ForeignKey(blank=True, help_text='上级部门', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='department.department', verbose_name='上级部门'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='部门名称', max_length=20, unique=True, verbose_name='名称'),
        ),
    ]
