# Generated by Django 4.1.7 on 2023-06-07 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0003_alter_department_superior_alter_department_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, default='', help_text='部门', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='department.department', verbose_name='部门')),
                ('five_copy', models.ForeignKey(blank=True, help_text='抄送人5', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='抄送人5')),
                ('five_examine', models.ForeignKey(blank=True, help_text='五级审批', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='五级审批')),
                ('four_copy', models.ForeignKey(blank=True, help_text='抄送人4', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='抄送人4')),
                ('four_examine', models.ForeignKey(blank=True, help_text='四级审批', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='四级审批')),
                ('one_copy', models.ForeignKey(blank=True, help_text='抄送人1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='抄送人1')),
                ('one_examine', models.ForeignKey(blank=True, help_text='一级审批', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='一级审批')),
                ('three_copy', models.ForeignKey(blank=True, help_text='抄送人3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='抄送人3')),
                ('three_examine', models.ForeignKey(blank=True, help_text='三级审批', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='三级审批')),
                ('two_copy', models.ForeignKey(blank=True, help_text='抄送人2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='抄送人2')),
                ('two_examine', models.ForeignKey(blank=True, help_text='二级审批', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='二级审批')),
            ],
            options={
                'verbose_name': '审批表',
                'verbose_name_plural': '审批表',
                'db_table': 'tb_examine',
            },
        ),
        migrations.CreateModel(
            name='OverTime',
            fields=[
                ('examine_id', models.BigIntegerField(help_text='审批编号', primary_key=True, serialize=False, unique=True, verbose_name='审批编号')),
                ('data', models.DateTimeField(help_text='提交时间', verbose_name='提交时间')),
                ('reason', models.CharField(help_text='事由', max_length=32, verbose_name='事由')),
                ('start_data', models.DateTimeField(help_text='开始时间', verbose_name='开始时间')),
                ('end_data', models.DateTimeField(help_text='结束时间', verbose_name='结束时间')),
                ('duration', models.CharField(help_text='时长', max_length=16, verbose_name='时长')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('department', models.ForeignKey(default='美蓝', help_text='部门', on_delete=django.db.models.deletion.SET_DEFAULT, to='department.department', verbose_name='部门')),
                ('examines', models.ForeignKey(default='', help_text='审批流程', on_delete=django.db.models.deletion.SET_DEFAULT, to='examine.examine', verbose_name='审批数据')),
            ],
            options={
                'verbose_name': '加班表',
                'verbose_name_plural': '加班表',
                'db_table': 'tb_overtime',
            },
        ),
    ]
