# Generated by Django 4.1.7 on 2023-06-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_superior_alter_department_name'),
        ('examine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examine',
            name='department',
            field=models.ForeignKey(help_text='部门', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='department.department', verbose_name='部门'),
        ),
    ]
