# Generated by Django 4.1.7 on 2023-06-08 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examine', '0002_alter_examine_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examine',
            name='one_examine',
            field=models.ForeignKey(help_text='一级审批', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='一级审批'),
        ),
    ]
