# Generated by Django 4.1.7 on 2023-06-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_superior_alter_department_name'),
        ('examine', '0003_alter_examine_one_examine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='department',
            field=models.ForeignKey(help_text='部门', on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='examines',
            field=models.ForeignKey(default='', help_text='审批流程', on_delete=django.db.models.deletion.CASCADE, to='examine.examine', verbose_name='审批数据'),
        ),
    ]
