# Generated by Django 4.1.7 on 2023-06-08 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0004_alter_overtime_department_alter_overtime_examines'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='_data',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='提交日期', verbose_name='提交日期'),
            preserve_default=False,
        ),
    ]
