# Generated by Django 4.1.7 on 2023-06-09 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examine', '0005_overtime__data'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='name',
            field=models.ForeignKey(blank=True, help_text='提交人', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
    ]
